/**
 * This maps error constants with error codes.
 * @type {{}}
 */
module.exports = {
    NO_TOKEN: 101,
    INVALID_TOKEN: 102,
    INVALID_USER: 103,
    NOT_ACTIVE_USER: 104,
    EMPTY_STRING: 105,
    MOBILE_NUMBER_ALREADY_EXIST: 106,
    ACCESS_DENIED: 107,
    EMAIL_ALREADY_EXIST: 108,
    INVALID_EMAIL: 109,
    ACCOUNT_DEACTIVATE: 110,
    PASSWORD_DOES_NOT_MATCH: 111,
    INVALID_EMAIL_OR_PASSWORD_KEY: 112,
    LOGIN_FAILED: 113,
    DATA_NOT_FOUND: 114,
    FILE_UPLOAD_ERROR: 115,
    INVALID_FILE_TYPE: 116,
    INVALID_OTP: 117,
    INVALID_USER_KEY: -134,
    ADD_USER_ERROR: -136,
    UPDATE_USER_ERROR: -178,
    INCORRECT_PASSWORD: -179,
    MOBILE_ALREADY_EXISTS: 180,
    DUPLICATE_ENTRY_ERROR: 11000,

    // Server related error codes
    NOT_FOUND: 404,
    UNKNOWN_ERROR: 520,

    //Http error codes.
    HTTP_SUCCESS: 200,
    HTTP_FAILED: 400,
}
